  version: '3'
  
  services:
    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "8080:80"
      networks:
        my_network:
          ipv4_address: 10.10.10.2
  
    postgres:
      image: postgres
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      networks:
        my_network:
          ipv4_address: 10.10.10.3
  
  volumes:
    pgdata:
  
  networks:
    my_network:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 10.10.10.0/28
