---


- hosts: 192.168.56.3
  become: true
  vars:
       user: alyona
       home_dir: "/home/{{ user }}"
       auth_key_file: "{{ home_dir }}/.ssh/authorized_keys"
       ssh_public: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tasks:
    - name: New user
      user:
        name: "{{ user }}"
        shell: /bin/bash
        create_home: yes
    - name: Add SSH public key to auth_keys
      authorized_key:
         user: "{{ user }}"
         key: "{{ ssh_public }}"
         state: present
         exclusive: yes
         manage_dir: yes
         path: "{{ auth_key_file }}"
    - name: Disable SSH passwd auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: restart sshd
    - name: Create dir in /opt/
      file:
        path: /opt/new_directory
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"

  handlers:

    - name: restart sshd
      service:
        name: sshd
        state: restarted
